name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 --configuration=ci
      - run: npx nx affected -t build --parallel=3
  e2e:
    if: ${{ false }} # TODO: e2e is failed now since jest-babel configuration is incorrect, will be fixed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx affected -t e2e
        env:
          # thest are only for testing, DO NOT USE IT FOR OTHER PURPOSE!!
          VITE_MOCK_WALLET_PRIVATE_KEY: '0x8b806ec6cc2cbc6f75e1e0a0b020dba4d02f1a8578b9a8e2fb1f53f5a1c83e99'
          VITE_INFURA_PROJECT_ID: '25e33bb59b0b4803813c8f238cceb14e'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screen-records
          path: /home/runner/work/tw-did/tw-did/dist/cypress/apps/*/videos/*.mp4
  acceptance:
    if: ${{ false }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx affected -t acceptance
